image:  
  name: rflume/terraform-aws-ansible:latest
  #entrypoint:
    #- '/usr/bin/env'
    #- 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - validate
  - plan
  - apply

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  GITLAB_ACCESS_TOKEN: "QKLUtkX_wugU5gMkwYsz"
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY

#cache:
  #paths:
    #- terraform/.terraform

before_script:
  - rm -rf terraform/.terraform
  - echo “$SSH_KEY_PATH” > /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa
  #- 'which ssh-agent || ( apt-get install -qq openssh-client )'
  #- eval $(ssh-agent -s) 
  #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add 
  #- mkdir -p ~/.ssh
  #- chmod 700 ~/.ssh
  #- cd terraform/
  #- terraform --version
  #- terraform init -input=false 


validate:
  stage: validate
  script:
    - cd terraform
    - terraform init
    - terraform validate
  #artifacts:
    #name: plan
    #paths:
      #- terraform/planfile
  #only:
    #- branches


plan:
  stage: plan
  script:
    - cd terraform
    - terraform init
    - terraform plan -out "planfile"
    #- terraform plan
  artifacts:
    paths:
      - terraform/planfile

#build:
  #stage: plan
  #script:
    #- terraform plan -out "planfile"
    #name: plan
      #- "planfile"
  #only:
    #- master


apply:
  stage: apply
  script:
    - cd terraform
    - terraform init
    #- terraform apply -auto-approve
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
  #only:
    #changes:
      #- terraform/*


