image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


variables:
  PLAN: envs/plan.tfplan
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN

cache:
  paths:
    - .terraform

before_script:
  - terraform --version
  - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate
  only:
    - branches


plan:
  stage: plan
  script:
    - terraform plan -out $PLAN

#build:
  #stage: plan
  #script:
    #- terraform plan -out $PLAN
  #artifacts:
    #name: plan
    #paths:
      #- $PLAN
  #only:
    #- master


apply:
  stage: apply
  script:
    - terraform apply -input=false $PLAN
  #dependencies:
    #- build
  when: manual
  only:
    - master


