image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN

cache:
  paths:
    - .terraform

before_script:
  - cd terraform/
  - terraform --version
  - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate
  artifacts:
    name: plan
    paths:
      - terraform/planfile
  #only:
    #- branches


plan:
  stage: plan
  script:
    #- terraform plan -out "planfile"
    - terraform plan

#build:
  #stage: plan
  #script:
    #- terraform plan -out "planfile"
  #artifacts:
    #name: plan
    #paths:
      #- "planfile"
  #only:
    #- master


apply:
  stage: apply
  script:
    - terraform apply -auto-approve
    #- terraform apply -input=false "planfile"
  #dependencies:
    #- plan
  #when: manual
  #only:
    #changes:
      #- terraform/*


