image: 
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  GITLAB_ACCESS_TOKEN: "QKLUtkX_wugU5gMkwYsz"
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY

cache:
  paths:
    - terraform/.terraform

before_script:
  - rm -rf terraform/.terraform
  #- 'which ssh-agent || ( apt-get install -qq openssh-client )'
  #- eval $(ssh-agent -s) 
  #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add 
  #- mkdir -p ~/.ssh
  #- chmod 700 ~/.ssh
  #- cd terraform/
  #- terraform --version
  #- terraform init -input=false -backend-config=access_key=AWS_ACCESS_KEY_ID -backend-config=secret_key=AWS_SECRET_ACCESS_KEY
  - terraform init -input=false 

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate
  artifacts:
    name: plan
    paths:
      - terraform/planfile
  #only:
    #- branches


plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
    #- terraform plan

#build:
  #stage: plan
  #script:
    #- terraform plan -out "planfile"
  #artifacts:
    #name: plan
    #paths:
      #- "planfile"
  #only:
    #- master


apply:
  stage: apply
  script:
    #- terraform apply -auto-approve
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
  #only:
    #changes:
      #- terraform/*


